name: deploy-ui-to-testnet
on:
  workflow_dispatch:
    inputs:
      maintenance:
        type: boolean
        description: Deploy in maintenance mode?
        required: true
        default: false
      branch:
        type: string
        description: Target branch
        required: true
        default: "develop"
jobs:
  deploy-ui-to-testnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: amondnet/vercel-action@v20
        id: vercel-action-testnet
        with:
          scope: ${{ secrets.AXELAR_TEAM_ID_VERCEL }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_BRIDGET_TESTNET_PROJECT_ID }}
          vercel-args: "--prod --build-env REACT_APP_UNDER_MAINTENANCE=${{github.event.inputs.maintenance}}"
          alias-domains: |
            bridge.testnet.axelar.dev
            axelar-satellite-testnet.vercel.app
            testnet.satellite.money
        env:
          REACT_APP_UNDER_MAINTENANCE: ${{github.event.inputs.maintenance}}
